/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        command: {
          bg: '#F4F8FC',
          card: '#FFFFFF',
          border: '#D7E5EF',
          'border-bright': '#93C5FD',
          subtle: '#EAF2F8',
          surface: '#FFFFFF',
          text: '#0F172A',
          muted: '#475569',
          faint: '#64748B',
          navy: '#0B1F33',
        },
        navy: {
          950: '#071321',
          900: '#0B1F33',
          800: '#102A43',
          700: '#163A5F',
          600: '#1F4B78',
          500: '#2A6496',
        },
        sky: {
          50: '#F0F9FF',
          100: '#E0F2FE',
          200: '#BAE6FD',
          300: '#7DD3FC',
          400: '#38BDF8',
          500: '#0EA5E9',
          600: '#0284C7',
          700: '#0369A1',
          800: '#075985',
          900: '#0C4A6E',
        },
        mist: {
          50: '#F8FBFF',
          100: '#F4F8FC',
          200: '#EAF2F8',
          300: '#DCEAF4',
          400: '#CADEEB',
          500: '#B0C9DC',
        },
        aurora: {
          cyan: '#0EA5E9',
          teal: '#14B8A6',
          blue: '#0284C7',
          indigo: '#1E40AF',
          violet: '#3B82F6',
          emerald: '#10B981',
          sky: '#38BDF8',
          ocean: '#0F766E',
          amber: '#F59E0B',
        },
        alert: {
          critical: '#EF4444',
          high: '#F97316',
          moderate: '#F59E0B',
          low: '#10B981',
          info: '#0284C7',
        }
      },
      fontFamily: {
        sans: ['Outfit', 'Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      animation: {
        'aurora-slow': 'aurora 20s ease-in-out infinite alternate',
        'aurora-drift': 'aurora-drift 25s ease-in-out infinite alternate',
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'radar-sweep': 'radar-sweep 18s linear infinite',
        'glow-pulse': 'glow-pulse 3s ease-in-out infinite',
        'cloud-layer-1': 'cloud-layer-1 55s ease-in-out infinite alternate',
        'cloud-layer-2': 'cloud-layer-2 75s ease-in-out infinite alternate',
        'cloud-layer-3': 'cloud-layer-3 95s ease-in-out infinite alternate',
        'cloud-layer-4': 'cloud-layer-4 120s ease-in-out infinite alternate',
        'cloud-drift': 'cloud-drift 45s ease-in-out infinite alternate',
        'cloud-drift-slow': 'cloud-drift 65s ease-in-out infinite alternate',
        'cloud-drift-ultra': 'cloud-drift 90s ease-in-out infinite alternate',
        'sunlight-drift': 'sunlight-drift 75s ease-in-out infinite alternate',
        'haze-slow': 'haze-slow 50s ease-in-out infinite alternate',
        'float-slow': 'float-slow 4s ease-in-out infinite',
        'marker-breathe': 'marker-breathe 3s ease-in-out infinite',
        'gradient-slow': 'gradient-slow 12s ease-in-out infinite',
        'view-fade': 'view-fade 300ms cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'wind-flow': 'wind-flow 12s linear infinite',
      },
      keyframes: {
        aurora: {
          '0%': { transform: 'translate(0%, 0%) rotate(0deg) scale(1)' },
          '50%': { transform: 'translate(-4%, 6%) rotate(6deg) scale(1.1)' },
          '100%': { transform: 'translate(6%, -5%) rotate(-6deg) scale(1.05)' },
        },
        'aurora-drift': {
          '0%': { transform: 'translate(0%, 0%) scale(1)' },
          '50%': { transform: 'translate(5%, -6%) scale(1.15)' },
          '100%': { transform: 'translate(-5%, 4%) scale(0.95)' },
        },
        'radar-sweep': {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
        'glow-pulse': {
          '0%, 100%': { opacity: '0.4' },
          '50%': { opacity: '0.8' },
        },
        'cloud-layer-1': {
          '0%': { transform: 'translateX(-5%) translateY(0%) scale(1)' },
          '50%': { transform: 'translateX(4%) translateY(-1.5%) scale(1.04)' },
          '100%': { transform: 'translateX(7%) translateY(1%) scale(0.98)' },
        },
        'cloud-layer-2': {
          '0%': { transform: 'translateX(6%) translateY(0%) scale(0.96)' },
          '50%': { transform: 'translateX(-3%) translateY(2%) scale(1.03)' },
          '100%': { transform: 'translateX(-6%) translateY(-1%) scale(1)' },
        },
        'cloud-layer-3': {
          '0%': { transform: 'translateX(-3%) translateY(1%) scale(1.02)' },
          '50%': { transform: 'translateX(5%) translateY(-2%) scale(0.97)' },
          '100%': { transform: 'translateX(8%) translateY(0%) scale(1.04)' },
        },
        'cloud-layer-4': {
          '0%': { transform: 'translateX(4%) translateY(-1%) scale(1)' },
          '50%': { transform: 'translateX(-5%) translateY(1.5%) scale(1.05)' },
          '100%': { transform: 'translateX(-2%) translateY(-1%) scale(0.98)' },
        },
        'cloud-drift': {
          '0%': { transform: 'translateX(-4%) translateY(0%) scale(1)' },
          '50%': { transform: 'translateX(3%) translateY(-2%) scale(1.05)' },
          '100%': { transform: 'translateX(6%) translateY(2%) scale(0.98)' },
        },
        'sunlight-drift': {
          '0%': { transform: 'translate(0%, 0%) scale(1)', opacity: '0.8' },
          '50%': { transform: 'translate(4%, 3%) scale(1.08)', opacity: '0.95' },
          '100%': { transform: 'translate(-3%, -2%) scale(0.96)', opacity: '0.85' },
        },
        'haze-slow': {
          '0%': { transform: 'translateY(0%) scale(1)' },
          '50%': { transform: 'translateY(-3%) scale(1.04)' },
          '100%': { transform: 'translateY(2%) scale(0.97)' },
        },
        'float-slow': {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-4px)' },
        },
        'marker-breathe': {
          '0%, 100%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.04)' },
        },
        'gradient-slow': {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
        'view-fade': {
          '0%': { opacity: '0', transform: 'translateY(6px)' },
          '100%': { opacity: '1', transform: 'translateY(0px)' },
        },
        'wind-flow': {
          '0%': { strokeDashoffset: '0' },
          '100%': { strokeDashoffset: '-60' },
        },
      },
      boxShadow: {
        'atmospheric': '0 4px 20px -2px rgba(16, 42, 67, 0.06), 0 2px 6px -1px rgba(16, 42, 67, 0.04)',
        'atmospheric-lg': '0 12px 32px -4px rgba(16, 42, 67, 0.1), 0 4px 12px -2px rgba(16, 42, 67, 0.05)',
        'card-soft': '0 2px 10px rgba(15, 23, 42, 0.04)',
        'glass': '0 4px 20px -2px rgba(16, 42, 67, 0.06)',
        'glass-glow': '0 4px 20px -2px rgba(14, 165, 233, 0.12)',
        'glow-cyan': '0 0 15px -3px rgba(14, 165, 233, 0.25)',
        'glow-alert': '0 0 20px -3px rgba(239, 68, 68, 0.25)',
      },
    },
  },
  plugins: [],
}
