import type { EventType } from '../../types';

export const EVENT_KEYWORDS: Record<EventType, string[]> = {
  heavy_rainfall: [
    'rain',
    'heavy rain',
    'cloudburst',
    'downpour',
    'torrential',
    'precipitation',
    'deluge',
    'tipping bucket',
    'inundating rain',
    'water accumulation',
    'monsoon shower',
    'shower',
    'mm/hr',
  ],
  flood: [
    'flood',
    'flooding',
    'inundated',
    'inundation',
    'submerged',
    'water level',
    'embankment breach',
    'dyke',
    'water ingress',
    'river discharge',
    'waterlogging',
    'waterlogged',
    'danger mark',
    'culvert',
  ],
  cyclone: [
    'cyclone',
    'cyclonic',
    'deep depression',
    'depression',
    'gale winds',
    'sea swell',
    'storm surge',
    'landfall',
    'barometric drop',
    'knots',
    'rough sea',
    'seawall',
    'eye',
  ],
  thunderstorm: [
    'thunder',
    'thunderstorm',
    'lightning',
    'squall',
    'squall line',
    'cloud to ground',
    'kalbaishakhi',
    'convective cell',
    'hail',
    'hailstorm',
    'dbz',
    'thundercloud',
  ],
  heatwave: [
    'heatwave',
    'heat wave',
    'extreme heat',
    'hot conditions',
    'surface temperature',
    'heat index',
    'departure above normal',
    'scorching',
    'sunstroke',
    'heat exhaustion',
    'thermal',
  ],
  coldwave: [
    'coldwave',
    'cold wave',
    'extreme cold',
    'frost',
    'freezing',
    'dense fog',
    'visibility',
    'sub zero',
    'chill',
    'ground frost',
  ],
  landslide: [
    'landslide',
    'mudslide',
    'debris surge',
    'slope failure',
    'rockfall',
    'soil saturation',
    'washed out',
    'mudflow',
    'pore water',
    'hillside',
  ],
  high_wind: [
    'high wind',
    'gale force',
    'wind gust',
    'squally',
    'gale',
    'strong wind',
    'snapped branches',
  ],
  wind: [
    'wind',
    'breeze',
    'gust',
    'windy',
  ],
  storm: [
    'storm',
    'tempest',
    'cumulonimbus',
    'anvil',
  ],
  drought: [
    'drought',
    'dry spell',
    'rainfall deficit',
    'moisture deficit',
    'parched',
    'water deficit',
    'agrarian stress',
    'dry pond',
  ],
};
